[package]
name = "processing"
version = "0.1.0"
edition = "2018"

[dependencies]
uuid = { version = "0.7", features = ["v4", "serde"] }
downcast = "0.9.2"
serde = "1.0"
serde_dyn = "0.2.2"
erased-serde = "0.3.6"
daggy = "0.6.0"
