[package]
name = "processing"
version = "0.1.0"
edition = "2018"

[dependencies]
uuid = { version = "0.7", features = ["v4", "serde"] }
downcast = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
type-uuid = "0.1"
erased-serde = "0.3.6"
petgraph = "0.4.13"
