[package]
name = "atelier_loader"
version = "0.1.0"
authors = ["Karl Bergström <karl.anton.bergstrom@gmail.com>"]
edition = "2018"

[dependencies]
serde_dyn = "0.2.2"
slotmap = { version = "0.3", features = ["unstable"] }

schema = { path = "../schema", optional = true }
tokio = { version = "0.1", optional = true }
tokio-current-thread = { version = "0.1", optional = true }
tokio-executor = { version = "0.1", optional = true }
tokio-reactor = { version = "0.1", optional = true }
tokio-timer = { version = "0.2", optional = true }
capnp = { version = "0.9.4", features = ["rpc_try"], optional = true}
capnp-rpc = { version = "0.9.0", optional = true }
futures = { version = "0.1", optional = true }
log = { version = "0.4", optional = true }

[features]
default = ["rpc_loader"]
rpc_loader = ["schema", "tokio", "tokio-current-thread", "tokio-executor", "tokio-reactor", "tokio-timer", "capnp", "capnp-rpc", "futures", "log"]