[package]
name = "schema"
version = "0.1.0"
build = "build.rs"

[dependencies]
# capnp = "0.9.0"
capnp = { path = "../../capnproto-rust/capnp" }

[build-dependencies]
capnpc = { path = "../../capnproto-rust/capnpc"}