[package]
name = "schema"
version = "0.1.0"
build = "build.rs"

[dependencies]
# capnp = "0.9.0"
capnp = { git = "http://github.com/capnproto/capnproto-rust", branch = "master"}

[build-dependencies]
capnpc = { git = "http://github.com/capnproto/capnproto-rust", branch = "master"}