[package]
name = "asset-uuid"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro-hack = "0.5"
quote = "0.6"
syn = { version = "0.15", features = ["full"] }
uuid = "0.7"
