[package]
name = "atelier-importer"
version = "0.1.0"
edition = "2018"

[dependencies]
atelier-core = { path = "../core" }
uuid = { version = "0.7", features = ["v4", "serde"] }
downcast = "0.10"
serde = "1.0"
type-uuid = "0.1"
erased-serde = "0.3"
ron = "0.4"
bincode = "1.1"
inventory = "0.1"
